export const SEND_REQUEST = 'PIN_SEND_REQUEST';
export const SEND_REQUEST_FAILURE = SEND_REQUEST + '_FAILURE';
export const RECEIVE_ALL = 'PIN_RECEIVE_ALL';
export const RECEIVE_ONE = 'PIN_RECEIVE_ONE';
